export const projectItems = [
  {
    name: "Adventure",
    title: "Adventure website",
    image: "img/Adventure.png",
    exerpt: `Responsive website template`,
    git: `https://github.com/bogodars/Adventure`,
    url: `https://bogodars.github.io/Adventure/index.html`,
    category: ["all", "web"],
    tag: ["html,", "css,", "js"],
  },
  {
    name: "Travelix",
    title: "Travelix",
    image: "img/Travelix.png",
    exerpt: `Responsive website for hotels search and booking`,
    git: `https://github.com/bogodars/Travelix`,
    url: `https://bogodars.github.io/Travelix/`,
    category: ["all", "web"],
    tag: ["html,", "css,", "js"],
  },
  {
    name: "MoGo",
    title: "MoGo",
    image: "img/Mogo.png",
    exerpt: `Responsive website Creative digital agency`,
    git: `https://github.com/bogodars/MoGo`,
    url: `https://bogodars.github.io/MoGo/`,
    category: ["all", "web"],
    tag: ["html,", "css,", "jquery,", "slick-slider"],
  },
  {
    name: "The Roza",
    title: "The Roza ",
    image: "img/Rosa.png",
    exerpt: `Responsive website for restaurant menu template`,
    git: `https://github.com/bogodars/Roza`,
    url: `https://bogodars.github.io/Roza/`,
    category: ["all", "web"],
    tag: ["html,", "css,", "js,", "animations"],
  },
  {
    name: "Skinali",
    title: "Skinali ",
    image: "img/Skinali.png",
    exerpt: `Responsive website for small business order`,
    git: `https://github.com/bogodars/Roza`,
    url: `https://bogodars.github.io/Roza/`,
    category: ["all", "web"],
    tag: ["html,", "sass,", "jquery,", "slick"],
  },
  {
    name: "Mybrary",
    title: "Mybrary",
    image: "img/Mybrary.png",
    exerpt: `Web app that use MVC folder structure, Node + Express + MongoDb on Back-end. `,
    git: `https://github.com/bogodars/MoGo`,
    url: `https://bogodars.github.io/MoGo/`,
    category: ["all", "full-stack"],
    tag: ["html,", "css,", "node,", "express,", "mongo"],
  },
  {
    name: "Expensify",
    title: "Expensify",
    image: "img/Expensify.png",
    exerpt: `Web app with node and firebase on Backe-end and React and Redux on Front-end `,
    git: `https://github.com/bogodars/expensify-app`,
    url: `https://rocky-basin-83545.herokuapp.com/`,
    category: ["all", "full-stack"],
    tag: ["React,", "node,", "redux,", "sass,", "firebase"],
  },
  {
    name: "smartBrain",
    title: "smartBrain",
    image: "img/smart-brain.png",
    exerpt: `Full Stack Web app with  AI API that detects face on the uploaded picture `,
    git: `https://github.com/bogodars/expensify-app`,
    url: `https://rocky-basin-83545.herokuapp.com/`,
    category: ["all", "full-stack"],
    tag: ["React", "tachyons", "node", "express", "Postgres"],
  },
  {
    name: "Currency Converter",
    title: "Currency Converter",
    image: "img/Currency-Converter.png",
    exerpt: `Web app that can convert currency `,
    git: `https://github.com/bogodars/Currency-Converter`,
    url: `https://bogodars.github.io/Currency-Converter/`,
    category: ["all", "app"],
    tag: ["React", "css", "jest", "heroku"],
  },
  {
    name: "User Guide",
    title: "bet webside",
    image: "img/bet.png",
    exerpt: `bet webside with chat and user-guide `,
    git: `https://github.com/bogodars/user-guide`,
    url: `https://wonderful-haibt-7134b0.netlify.app/`,
    category: ["all", "web"],
    tag: ["React", "styled-components", "css", "reactour"],
  },
]
